/**
 * 영어 사전 — 화면 글자. 열쇠는 **한국어 글자 자체**다(i18n.ts 머리말).
 *
 * 🔴 열쇠 안의 `{0}` `{1}`(값 자리)과 `<b>`(굵은 글씨)는 번역문에도 **똑같이** 있어야 한다.
 *    빠뜨리면 화면에서 그 값이 조용히 사라진다. `node scripts/i18n-scan.mjs --check`가 잡는다.
 *    자리는 옮겨도 된다 — 「N건 중 M건」이 「M of N」이 되려면 옮겨야 한다. 그러라고 통문장이다.
 *
 * 용어는 규격 원문을 따른다: Submodel · SubmodelElement · ConceptDescription · semanticId · idShort.
 * 이 도구의 말: 지적 = finding · 위반 = error · 경고 = warning · 자동 고치기 = Auto-fix ·
 *   설비 = equipment · 공정 = process · 묶음 = group · 이관 대장 = relocation ledger · 수집 = collection.
 */
export const EN_MORE: Record<string, string> = {
  // ── addressList.ts — 현장에 넘기는 주소 목록(CSV)의 머리글 ──────────────
  인터페이스: 'Interface',
  프로토콜: 'Protocol',
  접속주소: 'Endpoint',
  '주소(NodeId)': 'Address (NodeId)',
  데이터타입: 'Data type',
  관측가능: 'Observable',
  최근값: 'Latest value',
  품질: 'Quality',
  수집시각: 'Collected at',
  모델연결: 'Model link',
  '이름 중복 ({0}곳)': 'Duplicate name ({0} places)',
  '이름 안 맞음': 'Name mismatch',
  예: 'Yes',
  아니오: 'No',

  // ── api.ts · main.tsx · model.ts ───────────────────────────────────────
  'API 서버에 연결할 수 없습니다 — 8080이 떠 있는지 확인하십시오 (개발: npm run dev:api).':
    'Cannot reach the API server — check that port 8080 is running (development: npm run dev:api).',
  'API 응답이 아닙니다 ({0}) — 개발 서버 프록시(vite.config.ts)에 이 경로가 빠져 있습니다.':
    'Not an API response ({0}) — this path is missing from the dev-server proxy (vite.config.ts).',
  '#root가 없습니다.': '#root is missing.',
  '{0} ×{1}대': '{0} ×{1}',

  // ── Splitter · TreeView ────────────────────────────────────────────────
  '{0} 너비 조절': 'Resize {0}',
  '끌어서 너비 조절 · 두 번 누르면 기본값': 'Drag to resize · double-click to reset',
  '이 요소의 지적 {0}건': '{0} finding(s) on this element',
  '아래에 지적 {0}건 (펼쳐서 확인)': '{0} finding(s) below (expand to see)',
  '{0} 메뉴': '{0} menu',

  // ── Hierarchy ──────────────────────────────────────────────────────────
  '회사 → 공정 → 설비를 한 트리로 그립니다 — 이 파일의 HierarchicalStructures 서브모델(IDTA 02011)에 저장되고, 왼쪽 트리 맨 위 ⚙·▦ 줄로도 보입니다. 회사 줄의 「＋ 공정」으로 공정을 만들고, 그 공정 줄의 「＋ 설비」로 설비를 넣습니다(올려 둔 파일에서 고르거나 「PC에서 가져오기」로 이 PC 폴더의 .aasx를 바로 올립니다).':
    'Company → process → equipment, drawn as one tree. It is stored in this file\'s HierarchicalStructures submodel (IDTA 02011) and also appears as the ⚙·▦ rows at the top of the tree on the left. Use "+ Process" on the company row to create a process, then "+ Equipment" on that process row to add equipment (pick an uploaded file, or use "Import from PC" to upload .aasx files from a folder on this PC).',
  '아직 아무것도 들어 있지 않습니다 — 위 줄의 「＋ 공정」 또는 「＋ 설비」로 넣습니다.':
    'Nothing here yet — add with "+ Process" or "+ Equipment" on the row above.',
  '요소 {0}개': '{0} elements',
  '이 설비 파일을 엽니다 — 지금 보는 파일 대신 그 파일로 바뀝니다':
    'Opens this equipment file — it replaces the file you are viewing',

  // ── Settings ───────────────────────────────────────────────────────────
  한국어: '한국어',
  '화면 글자를 한국어로 — 모든 글자가 한국어입니다': 'Switch the interface to Korean — everything is available in Korean',
  '고른 언어는 이 브라우저에 남습니다. 서버 설정이 아니라 보는 사람마다 따로입니다.':
    'Your choice is kept in this browser. It is not a server setting — each viewer chooses separately.',

  // ── AddSubmodel ────────────────────────────────────────────────────────
  추가: 'Add',
  '예: RollFormingSafety': 'e.g. RollFormingSafety',
  '버전 · 리비전 (administration){0}': 'Version · revision (administration){0}',
  '필수 서브모델 4종 중 하나입니다(KOSMO-AAS-4).': 'This is one of the four mandatory submodels (KOSMO-AAS-4).',
  '이미 「{0}」이(가) 있습니다 — 같은 이름이 둘이면 어느 것이 맞는 것인지 정해지지 않습니다.':
    '"{0}" already exists — with two of the same name it is undefined which one is the right one.',
  '지금 {0}종입니다 — 하나 더 넣으면 KOSMO 상한(8종)을 넘어 위반(KOSMO-AAS-4)이 됩니다.':
    'There are {0} now — one more exceeds the KOSMO limit of 8 and becomes an error (KOSMO-AAS-4).',
  '이 설비에 서브모델을 새로 만듭니다 — id는 규약대로 지어집니다':
    'Creates a new submodel for this equipment — the id is generated by convention',

  // ── Inspector ──────────────────────────────────────────────────────────
  '🔗 <b>{0}</b> 파일의 요소입니다 — 저장하면 <b>그 파일이</b> 바뀝니다. 지적(위반)은 그 파일을 열었을 때 보입니다.':
    '🔗 This element belongs to the file <b>{0}</b> — saving changes <b>that file</b>. Its findings appear when you open that file.',
  '{0} 줄 빼기': 'Remove the {0} row',
  '<b>용어 정의</b>입니다 — 서브모델 요소가 쓰는 이름의 뜻풀이이고, 요소의 {0}가 여기를 가리킵니다. 표준 사전(ECLASS·IEC CDD)에서 온 것은 그대로 두고, 도구가 만든 것은 아래에서 뜻풀이를 채우십시오 — 문서용 자료의 「정의」 열에 그대로 실립니다.':
    'This is a <b>concept description</b> — the definition of a name used by submodel elements; an element\'s {0} points here. Leave entries from standard dictionaries (ECLASS, IEC CDD) as they are, and fill in the definition below for the ones this tool created — it goes straight into the "Definition" column of the document assets.',
  '여기서는 <b>{0}</b>의 내용을 확인합니다. 값은 아래 요소(Property 등)에 있습니다 — 트리에서 펼쳐 고르십시오.':
    'This shows the contents of <b>{0}</b>. The values live in the elements below (Property, etc.) — expand the tree and pick one.',
  '값 한꺼번에 입력 ({0}개)': 'Enter values in bulk ({0})',
  '바뀐 {0}개 저장': 'Save {0} changed',
  ' — 임시 그림입니다. 실제 장비 사진으로 바꾸십시오': ' — this is a placeholder image. Replace it with a real photo of the equipment',
  '붙어 있음: {0}': 'Attached: {0}',

  // ── ImportSubmodel ─────────────────────────────────────────────────────
  '원본 파일': 'Source file',
  '서브모델 가져오기': 'Import a submodel',
  '가져올 원본이 없습니다. 검증을 통과한 다른 AASX를 먼저 열어 두십시오.':
    'No source to import from. Open another AASX that passes validation first.',
  'id는 이 파일의 장비명에 맞게 다시 짓고, 쓰이는 ConceptDescription도 함께 가져옵니다.':
    'The id is regenerated for this file\'s equipment name, and the ConceptDescriptions it uses are imported with it.',
  '이 파일에 이미 「{0}」이(가) 있습니다': 'This file already has "{0}"',
  '바꾸기 — 지금 것을 지우고 가져온 것으로 대체합니다 (지금 것의 값은 사라집니다)':
    'Replace — delete the current one and use the imported one (the current values are lost)',
  '나란히 두기 — 「{0}_2」로 가져옵니다 (견줘 보고 하나를 지우십시오)':
    'Keep both — import as "{0}_2" (compare them and delete one)',
  '고른 서브모델을 통째로 복사해 옵니다 — id는 이 설비에 맞게 다시 지어지고 용어(CD)도 함께 옵니다':
    'Copies the chosen submodel in full — the id is regenerated for this equipment and its concept descriptions come with it',
  가져오기: 'Import',

  // ── Summary ────────────────────────────────────────────────────────────
  '{0}건': '{0}',
  '설비 (총 {0}대)': 'Equipment ({0} units in total)',
  '파일이 안 열린 설비 {0}건은 합계에 빠져 있습니다 — 열면 합산됩니다.':
    '{0} equipment item(s) with no open file are left out of the totals — open them to include them.',
  '<b>다만 비어 있는 서브모델 {0}개</b>({1}) — 규칙은 형식만 봅니다. 트리에서 골라 「요소 추가」, 또는 위 「다른 파일에서 가져오기」로 채우십시오.':
    '<b>However, {0} submodel(s) are empty</b> ({1}) — the rules only check form. Pick one in the tree and use "Add element", or fill it with "Import from another file" above.',
  '{0}위 「위반 {1}건」을 누르면 목록이 열리고, 항목을 누르면 그 요소로 갑니다.':
    '{0}Click "{1} errors" above to open the list; click an item to jump to that element.',
  '그중 {0}건은 위 「자동 고치기」로 바로 교정됩니다. ': '{0} of them can be fixed right away with "Auto-fix" above. ',
  '자동으로 고칠 수 있는 것은 없습니다 — 사람이 봐야 합니다. ': 'None of them can be fixed automatically — they need a person. ',
  '옮겼던 IDTA 공식 IRI를 원래대로 되돌립니다 — 지금 정책(KOSMO 우선)이면 다시 위반으로 잡힙니다':
    'Restores the relocated official IDTA IRIs — under the current policy (KOSMO first) they will be reported as errors again',
  '필수 서브모델이 빠졌습니다: <b>{0}</b> — 「다른 파일에서 가져오기」로 채울 수 있습니다.':
    'Mandatory submodels are missing: <b>{0}</b> — you can add them with "Import from another file".',

  // ── AddElement ─────────────────────────────────────────────────────────
  '묶음: 요소들을 폴더처럼 담습니다': 'Collection: holds elements like a folder',
  '목록: 같은 종류를 순서 있게 담습니다': 'List: holds elements of one kind, in order',
  '값 하나 (숫자·글자 등)': 'A single value (number, text, …)',
  '여러 언어 글 (한/영 이름·설명)': 'Multi-language text (names and descriptions in KO/EN)',
  '범위: 최소~최대 (온도·압력)': 'Range: min to max (temperature, pressure)',
  '첨부 파일 (사진·PDF·도면)': 'Attached file (photo, PDF, drawing)',
  '{0} 아래에 추가': 'Add under {0}',
  '새 요소 이름 (idShort)': 'New element name (idShort)',
  'CamelCase 영문': 'CamelCase, Latin letters',
  '영문자로 시작하는 2자 이상이어야 합니다(AASd-002).': 'Must start with a letter and be at least 2 characters (AASd-002).',
  'semanticId는 붙이지 않습니다. 만든 뒤 린터가 지적하면 「자동 고치기」가 규약대로 채웁니다.':
    'No semanticId is attached. If the linter flags it afterwards, "Auto-fix" fills it in by convention.',
  '고른 종류로 요소를 만들어 지금 자리에 넣습니다': 'Creates an element of the chosen kind at this position',

  // ── FindingsPanel ──────────────────────────────────────────────────────
  참고: 'Info',
  '위반 {0}건{1}': '{0} errors{1}',
  '· 경고 {0}건': '· {0} warnings',
  '{0} {1}건{2}': '{0} {1}{2}',
  '— 반드시 고칩니다(KOSMO 규칙)': '— must be fixed (KOSMO rules)',
  '위반이 없습니다 — KOSMO 규칙을 모두 지켰습니다.':
    'No violations — all KOSMO rules are met.',
  '— 확인하고 필요하면 「자동 고치기」': '— review, and use "Auto-fix" if needed',
  '경고가 없습니다.': 'No warnings.',
  '참고 {0}건 — 고칠 것 없음, 알아 둘 사실만': '{0} info item(s) — nothing to fix, just facts to know',
  '자동으로 고치지 못한 것 {0}건': '{0} could not be fixed automatically',
  '「자동 고치기」가 규약대로 교정합니다 — 경고도 함께': '"Auto-fix" corrects these by convention — warnings too',
  '자동 고치기 대상': 'Fixable automatically',
  '정책: {0}': 'Policy: {0}',

  // ── Summary — 이관 대장 ────────────────────────────────────────────────
  'IDTA 공식 IRI를 자체 IRI로 옮긴 것 <b>{0}건</b>이 <b>이관 대장</b>에 있습니다(KOSMO 우선 정책 — Validator가 공식 IRI를 거부하기 때문). 내려받는 .aasx 안에 함께 들어가고 검증 결과서에도 실립니다.':
    '<b>{0}</b> official IDTA IRI(s) relocated to in-house IRIs are recorded in the <b>relocation ledger</b> (KOSMO-first policy — the Validator rejects official IRIs). The ledger is packed into the downloaded .aasx and listed in the validation report.',
  // ── Rules — 규칙과 규약 ────────────────────────────────────────────────
  교정: 'Fix',
  규칙: 'Rule',
  '규칙 목록을 받지 못했습니다.': 'Could not load the rule list.',
  '불러오는 중…': 'Loading…',
  '이 도구가 지키는 규칙과 규약': 'Rules and conventions this tool enforces',
  '규칙 {0}종 · 자동 교정 {1}종': '{0} rules · {1} with automatic fixes',
  '합격은 누가 정하는가': 'Who decides acceptance',
  '규약 — 새로 만들 때 이 형식을 따릅니다': 'Conventions — new items follow these forms',
  '전부 <b>기본값</b>입니다(코드에 심어 둔 실측 기준).': 'All are <b>defaults</b> (measured baselines built into the code).',
  '정책 파일로 바꾼 항목: <b>{0}</b>': 'Overridden by the policy file: <b>{0}</b>',
  '규정이 충돌할 때 — 무엇을 골랐는가': 'When regulations conflict — what was chosen',
  'KTL 규정과 KOSMO Validator가 정면으로 부딪히는 자리입니다. 한쪽을 조용히 고르지 않고<b> 지금 무엇을 골랐는지 </b>보여 줍니다.':
    'These are the places where the KTL regulation and the KOSMO Validator directly contradict each other. Rather than silently picking a side, this shows<b> what is chosen right now</b>.',
  '← 지금 이것': '← current',
  '규칙 {0}종': '{0} rules',
  '규칙 전부를 봅니다': 'Show all rules',
  'L1 — 파일(OPC 패키지) 규칙': 'L1 — file (OPC package) rules',
  'L2 — AAS 메타모델 제약(AASd-*)': 'L2 — AAS metamodel constraints (AASd-*)',
  'L3 — KOSMO 사업 규칙': 'L3 — KOSMO business rules',
  전체: 'All',
  계층: 'Layer',
  근거: 'Source',
  자동: 'Auto',
  사람: 'Manual',
  // ── FixPreview — 자동 고치기 미리보기 ──────────────────────────────────
  '이 파일': 'This file',
  '전체 고르기': 'Select all',
  대상: 'Target',
  '자동 고치기 — 미리보기{0}': 'Auto-fix — preview{0}',
  '· 고칠 수 있는 {0}건{1}{2}': '· {0} fixable{1}{2}',
  ' ({0}바퀴)': ' ({0} passes)',
  ' · 파일 {0}개': ' · {0} files',
  '자동으로 고칠 수 있는 지적이 없습니다.': 'There are no findings that can be fixed automatically.',
  '체크한 것만 반영됩니다. 반영한 뒤에도 「↶ 되돌리기」로 한 번에 돌아옵니다.{0}':
    'Only the checked items are applied. You can still revert in one step with "↶ Undo".{0}',
  ' 설비 파일의 교정은 그 설비 파일에 저장됩니다 — 편집과 같은 길입니다.':
    ' Fixes to an equipment file are saved in that equipment file — the same path as editing.',
  '전부 고르기': 'Select all',
  '{0} · {1}건': '{0} · {1}',
  '설비 파일': 'Equipment file',
  '{0} 전체 고르기': 'Select all in {0}',
  무엇을: 'What',
  전: 'Before',
  후: 'After',
  '{0} {1} 고르기': 'Select {0} {1}',
  '(지움)': '(removed)',
  '이 중 <b>{0}건</b>은 IDTA 공식 IRI를 자체 IRI로 옮기는 교정입니다(KOSMO Validator가 공식 IRI를 거부하기 때문 — 정책 「KOSMO 우선」). 원본 IRI는 <b>이관 대장</b>에 남아 내려받는 .aasx에 함께 들어가고, 요약 화면에서 언제든 원본으로 되돌릴 수 있습니다.':
    '<b>{0}</b> of these relocate an official IDTA IRI to an in-house IRI (the KOSMO Validator rejects official IRIs — policy "KOSMO first"). The original IRI stays in the <b>relocation ledger</b>, is packed into the downloaded .aasx, and can be restored at any time from the summary screen.',
  '자동으로 못 고치는 것 {0}건 — 사람이 판단할 몫': '{0} cannot be fixed automatically — these need a person\'s judgement',
  '체크한 것만 고칩니다 — 반영한 뒤에도 헤더의 ↶로 한 번에 돌아옵니다':
    'Fixes only the checked items — you can still revert in one step with ↶ in the header',
  '고른 {0}건 반영': 'Apply {0} selected',
  // ── HierarchyTree — 구성 트리 ──────────────────────────────────────────
  예정: 'Planned',
  '{0} 이름': '{0} name',
  '이 줄 아래에 넣습니다': 'Adds under this row',
  넣기: 'Add',
  '영문으로 시작, 영문·숫자·밑줄 2자 이상.': 'Start with a letter; letters, digits and underscores, at least 2 characters.',
  '같은 자리에 같은 이름이 이미 있습니다.': 'The same name already exists at this position.',
  '넣을 파일 고르기': 'Choose a file to add',
  '— 올려 둔 파일 없음 —': '— no uploaded files —',
  '— 올려 둔 파일에서 —': '— from uploaded files —',
  '이 PC의 폴더에서 .aasx를 골라 올린 뒤 바로 넣습니다': 'Pick .aasx files from a folder on this PC, upload them and add them right away',
  '올리는 중…': 'Uploading…',
  'PC에서 가져오기': 'Import from PC',
  또는: 'or',
  '새 {0} 이름': 'New {0} name',
  대수: 'Quantity',
  '×n 한 줄 대신 이름_1…_n 파일로 각각 — 대별 수집이 목적이면 이쪽':
    'Separate files Name_1…Name_n instead of one ×n row — choose this to collect per unit',
  '고른 파일 또는 적은 이름으로 넣습니다': 'Adds using the chosen file or the typed name',
  '같은 자리에 같은 {0}이(가) 이미 있습니다 — 대수를 올리십시오.': 'The same {0} already exists at this position — raise the quantity instead.',
  '이 줄 아래에 설비(또는 부품)를 넣습니다': 'Adds equipment (or a part) under this row',
  '{0} — 올려 둔 파일': '{0} — uploaded file',
  '{0} — 이름만. 같은 이름으로 파일을 만들면 이어집니다': '{0} — name only. Create a file with the same name and it links up',
  '{0} — 파일이 열려 있지 않습니다': '{0} — the file is not open',
  '같은 이름으로 설비 파일을 만들면 저절로 이어집니다': 'Create an equipment file with the same name and it links up automatically',
  '이 설비 파일이 올라와 있지 않습니다 — 올리면 이어집니다': 'This equipment file has not been uploaded — upload it and it links up',
  '파일 안 열림': 'File not open',
  '{0}을(를) 빼면 그 밑 {1}은(는) 한 층 위로 올라옵니다': 'Removing {0} moves the {1} below it up one level',
  '이 목록에서 뺍니다 — 파일은 지워지지 않습니다': 'Removes it from this list — the file is not deleted',
  '파일 없는 층(공정·라인)을 만듭니다': 'Creates a level without a file (process, line)',
  '설비(또는 부품)를 넣습니다': 'Adds equipment (or a part)',
  // ── Collection — 현장 값 수집 ──────────────────────────────────────────
  '이 설비 파일을 엽니다 — 지금 보는 공정 파일 대신 그 파일로 바뀝니다':
    'Opens this equipment file — it replaces the process file you are viewing',
  '공정 파일은 수집 대상이 아닙니다 — 값은 <b>설비마다</b> 받습니다. 이 공정의 설비 {0}대 중 <b>{1}대 연결됨</b>.':
    'A process file is not a collection target — values are received <b>per equipment</b>. <b>{1} connected</b> out of {0} equipment in this process.',
  '아직 설비가 없습니다. 가운데 구성에서 「＋ 설비」로 넣으십시오.': 'No equipment yet. Add some with "+ Equipment" in the structure panel in the middle.',
  '파일 없음(예정)': 'No file (planned)',
  '이 설비에 한 번 접속해 값을 읽어 옵니다': 'Connects to this equipment once and reads its values',
  '그 설비 파일을 열고 현장 PLC 주소로 수집 연결을 만듭니다': 'Opens that equipment file and creates a collection link to the field PLC address',
  'PLC 연결…': 'Connect PLC…',
  '도구 안의 가상 PLC(시뮬레이션)에 바로 연결하고 한 번 수집합니다': 'Connects straight to the built-in virtual PLC (simulation) and collects once',
  '가상 PLC': 'Virtual PLC',
  '열기 →': 'Open →',
  '🔴 연결하면 그 설비 파일에 수집 연결(AID)이 더해져 <b>시연본</b>이 됩니다. 원본 참조모델은 그대로 두고 「호기별로 나누기」로 만든 호기에서 연결하는 것을 권합니다. 모은 값은 「레퍼런스 번들」의 <b>실동작 증빙</b>으로 실립니다.':
    '🔴 Connecting adds a collection link (AID) to that equipment file and turns it into a <b>demo copy</b>. Keep the original reference model as it is, and connect from the units created by "Split into units" instead. Collected values are included in the reference bundle as <b>operation evidence</b>.',
  '설비의 OPC UA 주소와 태그를 적으면 규격(IDTA-02017)대로 AID 서브모델을 지어 줍니다':
    'Enter the equipment\'s OPC UA address and tags, and an AID submodel is built to the specification (IDTA-02017)',
  '도구 안의 가상 PLC가 이 설비의 운전 데이터 이름대로 값을 흉내 냅니다 — 시연·재현용이며 값은 시뮬레이션입니다':
    'The built-in virtual PLC imitates values under this equipment\'s operational data names — for demos and reproduction; the values are simulated',
  ' · 값 대기 {0}': ' · {0} awaiting values',
  '연결됨 · 나쁜 태그 {0}{1}': 'Connected · {0} bad tag(s){1}',
  '연결됨{0}': 'Connected{0}',
  '수집주소목록.csv': 'collection-addresses.csv',
  '지금 한 번 접속해 값을 읽어 옵니다 — 주기 수집은 COLLECT_INTERVAL로 켭니다':
    'Connects once now and reads the values — periodic collection is enabled with COLLECT_INTERVAL',
  '이 설비에서 읽을 주소를 표 한 장으로 뽑습니다 — 시운전·검수에 넘기는 목록입니다':
    'Exports the addresses to read from this equipment as one table — the list handed over for commissioning and inspection',
  '접속 주소·태그를 고칩니다': 'Edit the endpoint and tags',
  '수집 연결(AID)을 지웁니다': 'Delete the collection link (AID)',
  '자동 수집 켜짐 — {0}초마다{1}': 'Automatic collection on — every {0} s{1}',
  '· 마지막 {0} ({1}건)': '· last {0} ({1})',
  '읽기 실패{0}': 'Read failed{0}',
  '설비에 붙어 읽었으나 아직 값이 올라오지 않았습니다. 고장이 아닙니다':
    'Connected and read, but no value has arrived yet. This is not a fault',
  '<b>표준 API로 내보내기</b> — 수집 {0}개 중 <b>{1}개</b>가 모델 요소와 이름이 맞습니다.':
    '<b>Exposed through the standard API</b> — <b>{1}</b> of the {0} collected items match a model element by name.',
  '{0}로 읽으면 그 자리에 현장 값이 보입니다.': 'Read with {0} and the field value appears in place.',
  '이름이 맞지 않아 못 얹은 것: {0}': 'Not applied because the name does not match: {0}',

  // ── NewPackage — 새로 만들기 ───────────────────────────────────────────
  '명판 — 제조사·모델명·일련번호': 'Nameplate — manufacturer, model, serial number',
  '인계 문서 — 매뉴얼·도면 첨부': 'Handover documents — manuals and drawings attached',
  '기술 사양': 'Technical data',
  '운전 데이터': 'Operational data',
  'BoM 구조 복잡 장비': 'Equipment with a complex BoM',
  '주기적 보전 중요 장비': 'Equipment where periodic maintenance matters',
  '에너지 집약 장비': 'Energy-intensive equipment',
  '시계열 모니터링 장비': 'Equipment monitored as time series',
  '모든 장비 공통': 'Common to all equipment',
  'OPC UA 연동 장비 (수집 연결)': 'Equipment connected over OPC UA (collection link)',
  '3D 모델 제공': '3D model provided',
  '설비 한 대 — 필수 서브모델 4종이 든 뼈대가 만들어집니다': 'One piece of equipment — creates a skeleton with the four mandatory submodels',
  '회사·공정으로 설비들을 묶는 파일 — 설비 상세는 담지 않고 주소로 가리킵니다':
    'A file that groups equipment by company or process — it holds no equipment detail and refers to it by address',
  '그룹(회사/공정)': 'Group (company/process)',
  '여러 설비·공정을 담는 단위입니다 — 회사·공정·라인 무엇이든 이름으로 정해집니다. 설비 내용은 각 설비 파일에 있고, 이 파일은 그것을 잇습니다.':
    'A unit that holds several pieces of equipment or processes — company, process or line, whatever the name says. Equipment content lives in each equipment file; this file links them.',
  '설비 한 대의 AAS입니다. 필수 서브모델 4종이 자동으로 들어갑니다.': 'The AAS of one piece of equipment. The four mandatory submodels are added automatically.',
  '① 이름 (회사·공정·라인)': '① Name (company, process, line)',
  '설비 이름': 'Equipment name',
  '예: OurFactory · WeldingLine': 'e.g. OurFactory · WeldingLine',
  '예: PressMachine': 'e.g. PressMachine',
  '영문으로 시작하고 영문·숫자·밑줄만 씁니다. 이 이름이 id에 그대로 들어갑니다.':
    'Start with a letter and use only letters, digits and underscores. This name goes into the id as is.',
  '필수 서브모델 — 자동 생성 (순서 고정)': 'Mandatory submodels — created automatically (fixed order)',
  '선택 서브모델 — 필요한 것만 체크': 'Optional submodels — tick only what you need',
  '설비 특화 서브모델 (직접 입력)': 'Equipment-specific submodels (type them in)',
  '쉼표로 구분 — 예: PressSafety (보통 1개)': 'Comma-separated — e.g. PressSafety (usually one)',
  '만들면 <b>{0}종</b>이 들어갑니다: {1}': 'This will create <b>{0}</b> submodels: {1}',
  '{0}종은 KOSMO 상한(8종)을 넘습니다 — 만들자마자 위반(KOSMO-AAS-4)이 됩니다. 설비 특화 서브모델을 줄이십시오.':
    '{0} exceeds the KOSMO limit of 8 — it is an error (KOSMO-AAS-4) the moment it is created. Reduce the equipment-specific submodels.',
  '② 구성 — 회사 → 공정 → 설비를 트리로': '② Structure — company → process → equipment as a tree',
  '회사 줄의 「＋ 공정」으로 공정을 만들고, <b>그 공정 줄의 「＋ 설비」</b>로 밑에 설비를 넣습니다. 설비는 올려 둔 파일에서 고르거나, <b>「PC에서 가져오기」</b>로 이 PC 폴더의 .aasx를 그 자리에서 올리거나, 아직 파일이 없으면 이름만 적습니다. 만든 뒤에도 같은 모양으로 고칩니다.':
    'Create a process with "+ Process" on the company row, then add equipment under it with <b>"+ Equipment" on that process row</b>. Pick equipment from uploaded files, upload .aasx files from a folder on this PC with <b>"Import from PC"</b>, or just type a name if there is no file yet. You can edit it the same way afterwards.',
  '(이름)': '(name)',
  '아직 비어 있습니다 — 위 줄의 「＋ 공정」부터. 빈 채로 만들고 나중에 넣어도 됩니다.':
    'Still empty — start with "+ Process" on the row above. You may also create it empty and add later.',
  '고급 — 묶음 자체의 서브모델': 'Advanced — submodels of the group itself',
  '묶음 파일에는 계층(HierarchicalStructures)만 들어갑니다. 묶음 자체의 명판 등이 더 필요하면 여기 적거나, 만든 뒤 「＋ 서브모델」로 더합니다.':
    'A group file contains only the hierarchy (HierarchicalStructures). If the group itself needs a nameplate or more, enter it here or add it afterwards with "+ Submodel".',
  '서브모델 이름': 'Submodel name',
  '쉼표로 구분 — 예: DigitalNameplate': 'Comma-separated — e.g. DigitalNameplate',
  '대표 사진은 <b>임시 그림</b>이 들어갑니다. 실제 사진으로 바꾸십시오 (AssetInformation을 고르면 바꿀 수 있습니다).':
    'A <b>placeholder image</b> is used as the thumbnail. Replace it with a real photo (select AssetInformation to change it).',
  '이 이름으로 새 파일을 만들어 서버에 올립니다': 'Creates a new file with this name and uploads it to the server',
  만들기: 'Create',
  // ── AddAid — 수집 연결 만들기 ──────────────────────────────────────────
  ' · 요소 {0}개 새로 세움': ' · {0} element(s) newly created',
  ' · 모델에 이미 있어 그대로 연결: {0}': ' · already in the model, linked as is: {0}',
  ' · ⚠ 모델과 이름이 안 맞는 태그 {0}개(표의 「모델연결」 열 참조)': ' · ⚠ {0} tag(s) do not match the model by name (see the "Model link" column)',
  '수집 연결을 {0}{1}{2}{3}': 'Collection link {0}{1}{2}{3}',
  바꿨습니다: 'updated',
  만들었습니다: 'created',
  '수집 연결 닫기': 'Close collection link',
  '← 수집 연결 만들기 — 설비에서 받아 오기': '← Create a collection link — receive from equipment',
  '<b>{0}</b> ──▶ [이 도구] ──▶ [MES·SCADA]{1}': '<b>{0}</b> ──▶ [this tool] ──▶ [MES·SCADA]{1}',
  '[설비·PLC]': '[Equipment·PLC]',
  '↑ 지금 여기를 설정합니다': '↑ you are configuring this part',
  '설비에 붙어 태그를 고르면 <b>AID 서브모델</b>(IDTA-02017)을 규격대로 만듭니다.':
    'Connect to the equipment and pick tags, and an <b>AID submodel</b> (IDTA-02017) is built to the specification.',
  '{0} 설비(PLC)의 OPC UA 주소{1}': '{0} OPC UA address of the equipment (PLC){1}',
  '내가 접속하러 갈 곳': 'where this tool connects to',
  '접속 주소': 'Endpoint',
  '그 주소에 붙어 설비가 내주는 태그 목록을 읽어 옵니다 — 값을 바꾸지 않습니다':
    'Connects to that address and reads the list of tags the equipment exposes — it changes no values',
  '훑는 중…': 'Browsing…',
  '설비에서 불러오기': 'Load from equipment',
  '<b>여기는 설비가 아니라 이 도구 자신입니다.</b> 이 주소는 우리가 상위 앱(MES·SCADA)에 값을 <b>내주는</b> 주소입니다 — 여기서 보이는 것은 설비 태그가 아니라 열려 있는 AAS 파일의 내용(제조사명·일련번호 같은 명판 정보)입니다.<br/>수집할 곳은 <b>설비(PLC)의 주소</b>입니다. 예: {0}<br/>장비 없이 시험만 해 보려면 가상 PLC를 띄우십시오 — {1}':
    '<b>This is not equipment — it is this tool itself.</b> This is the address where we <b>serve</b> values to upstream applications (MES, SCADA); what you see here is not equipment tags but the contents of the open AAS files (nameplate information such as manufacturer and serial number).<br/>The place to collect from is <b>the equipment (PLC) address</b>. For example: {0}<br/>To try it without real equipment, start the virtual PLC — {1}',
  '{0} 수집할 태그{1}': '{0} Tags to collect{1}',
  '{0}개 담김': '{0} added',
  '태그 {0}개': '{0} tags',
  '· 너무 많아 일부만': '· too many, showing part',
  '훑어 온 태그를 모두 고릅니다': 'Selects every tag that was browsed',
  '전체 선택': 'Select all',
  '고른 태그를 아래 목록으로 가져옵니다 — 이름·단위는 거기서 고칠 수 있습니다':
    'Moves the selected tags to the list below — you can edit names and units there',
  '고른 {0}개 담기': 'Add {0} selected',
  '위에 주소를 넣고 <b>「설비에서 불러오기」</b>를 누르면 태그를 골라 담을 수 있습니다.':
    'Enter the address above and press <b>"Load from equipment"</b> to pick tags.',
  '태그 {0} 이름': 'Tag {0} name',
  '태그 {0} 주소': 'Tag {0} address',
  '태그 {0} 타입': 'Tag {0} type',
  '이 줄을 뺍니다': 'Removes this row',
  '태그 {0} 지우기': 'Delete tag {0}',
  '설비에 붙지 않고 태그 주소를 직접 적습니다 — 주소를 이미 아는 경우':
    'Type tag addresses directly without connecting — for when you already know them',
  '+ 손으로 입력': '+ Enter manually',
  '⚠ {0}개는 모델에 없는 이름 — {1}': '⚠ {0} name(s) are not in the model — {1}',
  '자리를 함께 만듭니다': 'their places will be created too',
  '값이 밖으로 안 나갑니다': 'their values will not be exposed',
  '자세히 — 모델에 없는 항목의 자리': 'Details — places for items missing from the model',
  '모델에 없는 항목의': 'For items missing from the model,',
  '자리도 함께 만들기': 'create their places too',
  대분류: 'Category',
  소분류: 'Subcategory',
  'OperationalData 아래 이 두 칸으로 묶어 만듭니다. 이미 있는 이름은 건드리지 않고, 값 칸에는 예시값이 들어갑니다(규격이 빈 칸을 위반으로 봅니다).':
    'They are created under OperationalData, grouped by these two fields. Existing names are left untouched, and value fields get an example value (the specification treats an empty value as an error).',
  '⚠ 이렇게 만든 항목은 나중에 <b>「연결삭제」로 지워지지 않습니다.</b> 필요 없어지면 트리에서 직접 지워야 합니다.':
    '⚠ Items created this way are <b>not removed by "Delete link"</b> later. When they are no longer needed, delete them in the tree yourself.',
  '적은 주소와 태그로 AID 서브모델(IDTA-02017)을 규격대로 만듭니다 — 이미 있으면 바꿔치웁니다':
    'Builds an AID submodel (IDTA-02017) to the specification from the entered address and tags — replaces an existing one',
  '만들기{0}': 'Create{0}',
  ' ({0}개)': ' ({0})',
  // ── DocAssets — 문서용 자료 ────────────────────────────────────────────
  '그림을 읽지 못했습니다.': 'Could not read the image.',
  '캔버스를 열지 못했습니다.': 'Could not open a canvas.',
  'PNG로 바꾸지 못했습니다.': 'Could not convert to PNG.',
  'IDTA 원본: {0}': 'IDTA original: {0}',
  '그림을 받지 못했습니다.': 'Could not get the diagram.',
  '표를 복사했습니다. 문서에 붙여넣으십시오(Ctrl+V).': 'Table copied. Paste it into your document (Ctrl+V).',
  '복사가 막혔습니다. 「CSV 내려받기」를 쓰십시오.': 'Copying was blocked. Use "Download CSV" instead.',
  전체구성도: 'overview-diagram',
  '그림을 복사했습니다. 문서에 붙여넣으십시오(Ctrl+V).': 'Diagram copied. Paste it into your document (Ctrl+V).',
  '복사가 막혔습니다. 「PNG 내려받기」를 쓰십시오.': 'Copying was blocked. Use "Download PNG" instead.',
  '{0} — 가이던스 부속 자료': '{0} — guidance supplement',
  '이 문서는 AASX 파일에서 자동으로 뽑은 사실입니다. ': 'This document contains facts extracted automatically from the AASX file. ',
  '가이던스 문장(특징·활용방안·활용 시나리오)은 사람이 작성합니다. ': 'The guidance text (features, uses, usage scenarios) is written by a person. ',
  '필요한 부분을 골라 가이던스 문서로 복사해 쓰십시오.': 'Copy the parts you need into your guidance document.',
  '그림 {0} {1} 서브모델 UML 다이어그램': 'Figure {0} UML diagram of the {1} submodel',
  '표 {0} {1} - {2}': 'Table {0} {1} - {2}',
  '표 생략 — {0}': 'Table omitted — {0}',
  '외부 참조모델: {0}': 'External reference model: {0}',
  '(파일에 없음 — 확인해 넣으십시오)': '(not in the file — check and fill in)',
  ' · 참조 용어사전: {0}': ' · Reference dictionary: {0}',
  ' · 요소 수: {0}개': ' · Elements: {0}',
  '사람이 채울 자리': 'To be filled in by a person',
  '{0} 가이던스 부속 자료': '{0} guidance supplement',
  '{0}_가이던스_부속자료.docx': '{0}_guidance_supplement.docx',
  '문서를 내려받았습니다. 워드·한글에서 열어 필요한 부분을 복사하십시오.':
    'Document downloaded. Open it in a word processor and copy the parts you need.',
  '문서를 만들지 못했습니다.': 'Could not create the document.',
  '문서용 자료 — 가이던스에 붙여넣기': 'Document assets — paste into your guidance',
  '규정 §13은 <b>모든 서브모델에 UML Diagram 첨부</b>(주의사항 3)를 요구합니다. 여기서 뽑아 문서에 붙여넣으십시오. <b>문서 문장은 도구가 쓰지 않습니다</b> — 파일에 있는 사실만 그립니다.':
    'Regulation §13 requires <b>a UML diagram attached for every submodel</b> (note 3). Export them here and paste them into the document. <b>The tool does not write the document text</b> — it only draws the facts in the file.',
  '전체 구성도 (AAS + 서브모델)': 'Overview diagram (AAS + submodels)',
  '그림을 클립보드에 PNG로 담습니다 — 워드·한글에 Ctrl+V로 붙습니다': 'Copies the diagram to the clipboard as PNG — paste into a word processor with Ctrl+V',
  '그림 복사': 'Copy diagram',
  '그림을 PNG 파일로 내려받습니다': 'Downloads the diagram as a PNG file',
  'PNG 내려받기': 'Download PNG',
  '그림을 SVG로 내려받습니다 — 크기를 키워도 안 깨지지만 한글에서 안 붙는 경우가 있습니다':
    'Downloads the diagram as SVG — it scales without blurring, but some word processors (HWP) do not paste it',
  'SVG 내려받기': 'Download SVG',
  '서브모델 전부의 그림과 표를 한 .docx로 묶습니다 — A4 용지·그림 크기가 고정됩니다':
    'Bundles the diagrams and tables of every submodel into one .docx — A4 paper and diagram size are fixed',
  '문서 만드는 중…': 'Building document…',
  '문서 한 벌 내려받기 (.docx)': 'Download the full document (.docx)',
  '서브모델 {0}종의 그림과 표를 한 파일에': 'Diagrams and tables of {0} submodels in one file',
  '한글(HWP)·워드에는 <b>그림 복사</b>(PNG)가 안전합니다. SVG는 크기를 키워도 안 깨지지만 한글에서 제대로 안 붙는 경우가 있습니다.':
    'For HWP and Word, <b>Copy diagram</b> (PNG) is the safe choice. SVG scales without blurring but sometimes does not paste properly into HWP.',
  '구성요소 상세 정보 테이블': 'Element detail table',
  '표를 클립보드에 담습니다 — 워드·한글·엑셀에 표 모양 그대로 붙습니다': 'Copies the table to the clipboard — it pastes as a table into Word, HWP and Excel',
  '표 복사': 'Copy table',
  '표를 CSV로 내려받습니다 — 엑셀에서 열 수 있게 BOM을 붙입니다': 'Downloads the table as CSV — with a BOM so it opens in Excel',
  'CSV 내려받기': 'Download CSV',
  '{0}행': '{0} rows',
  '이 서브모델은 <b>표를 만들지 않습니다.</b> 대신 아래 정보를 가이던스에 적습니다.':
    'This submodel <b>produces no table.</b> Write the information below in your guidance instead.',
  '외부 참조모델': 'External reference model',
  '파일에 없음 — 확인해 넣으십시오': 'not in the file — check and fill in',
  '참조 용어사전': 'Reference dictionary',
  '요소 수': 'Elements',
  '{0}개': '{0}',
  '<b>사람이 채울 자리</b> — 도구는 지어내지 않습니다:': '<b>To be filled in by a person</b> — the tool does not make this up:',

  // ── BundlePanel — 레퍼런스 번들 ────────────────────────────────────────
  '만드는 중…': 'Building…',
  '「{0}」을(를) {1}에 넣었습니다 — 번들을 다시 열어도 남습니다.': 'Added "{0}" to {1} — it stays when the bundle is reopened.',
  '{0}\n\n번들 첨부에서 지웁니다. 계속할까요?': '{0}\n\nThis removes it from the bundle attachments. Continue?',
  '레퍼런스 번들 {0}': 'Reference bundle {0}',
  번들: 'Bundle',
  제목: 'Title',
  버전: 'Version',
  '수집 기록이 어디서 왔는지 — 기록서·README·manifest에 찍힙니다': 'Where the collection record came from — printed in the record, the README and the manifest',
  '증빙 수준': 'Evidence level',
  '자동 ({0})': 'Auto ({0})',
  미지정: 'unspecified',
  'A 현장 적용': 'A Applied on site',
  'B 실장비 재현': 'B Reproduced on real equipment',
  'C 시뮬레이션': 'C Simulation',
  비움: 'Leave empty',
  '어느 기간의 수집값을 실을지 — 시험 중 쌓인 값을 빼고 싶을 때': 'Which period of collected values to include — for leaving out values gathered while testing',
  '증빙 기간': 'Evidence period',
  전부: 'All',
  '최근 10분': 'Last 10 minutes',
  '최근 30분': 'Last 30 minutes',
  '최근 1시간': 'Last hour',
  '최근 24시간': 'Last 24 hours',
  '공정 구성 + 설비 AASX + manifest(SHA256) + 폴더 골격을 ZIP 하나로 받습니다':
    'Downloads the process structure, the equipment AASX files, the manifest (SHA256) and the folder skeleton as one ZIP',
  '번들 내보내기 (.zip)': 'Export bundle (.zip)',
  '⚡ <b>시연본 {0}대 포함</b> — 수집 연결(AID)이 붙어 있습니다. 시연용으로는 맞지만,<b> 정식 번들</b>에는 연결이 없는 원본 참조모델을 넣으십시오. 내보내면 README와 manifest에도 표시됩니다.':
    '⚡ <b>{0} demo copy(ies) included</b> — they carry a collection link (AID). That is right for a demo, but for<b> the official bundle</b> use the original reference models without the link. The export marks this in the README and the manifest as well.',
  '파일 {0}{1}': '{0} file(s){1}',
  '예정 {0}': '{0} planned',
  '사전 점검': 'Pre-check',
  '위반 0건': '0 errors',
  '위반 있는 설비': 'Equipment with errors',
  'KOSMO는 검사하지 않지만 표준 검증기(aas-test-engines)는 오류로 보고, BaSyx는 그 하위를 버립니다':
    'KOSMO does not check this, but the standard validator (aas-test-engines) reports it as an error and BaSyx drops everything below it',
  '표준 AASd-120 {0}': 'Standard AASd-120 {0}',
  '공통 항목': 'Common items',
  '2대 이상이 함께 가진 운전 데이터': 'Operational data shared by two or more equipment',
  '확인할 점': 'To check',
  'semanticId 재사용': 'semanticId reuse',
  '{0} · 수준 {1}': '{0} · level {1}',
  '이어받은 기록': 'Carried-over record',
  '수집 기록': 'Collection record',
  '수집 기록 없음': 'No collection record',
  '① 구성과 준비 상태': '① Structure and readiness',
  '이 공정에 아직 설비가 없습니다. 「무엇으로 이루어졌나」에서 설비를 넣으십시오.':
    'This process has no equipment yet. Add equipment under "What it consists of".',
  '(최상위)': '(top level)',
  '눌러서 이 설비 파일을 엽니다': 'Click to open this equipment file',
  '파일이 없습니다 — 같은 이름으로 설비 파일을 만들면 이어집니다': 'No file — create an equipment file with the same name and it links up',
  '파일 없음': 'No file',
  '수집 연결(AID)이 붙은 시연본입니다 — 정식 번들에는 원본 참조모델을 넣으십시오':
    'A demo copy with a collection link (AID) — use the original reference model in the official bundle',
  '⚡ 수집 연결 · 시연본': '⚡ Collection link · demo copy',
  'SubmodelElementList 자식에 idShort — KOSMO는 통과지만 표준 검증기는 오류, BaSyx는 그 하위를 버립니다. 설비 파일을 열어 「자동 고치기」로 지우면 KOSMO에도 영향 없이 풀립니다':
    'idShort on SubmodelElementList children — KOSMO passes it, but the standard validator reports an error and BaSyx drops everything below. Open the equipment file and remove them with "Auto-fix"; KOSMO is not affected',
  '✓ 통과 · 경고 {0}': '✓ Pass · {0} warnings',
  '✕ 위반 {0}': '✕ {0} errors',
  '② 데이터 연계 — 운전 데이터 공통 항목{0}': '② Data linkage — common operational data items{0}',
  '설비 둘 이상이 함께 가진 항목만 봅니다 — 연계에 쓸 수 있는 것들입니다': 'Shows only items shared by two or more equipment — the ones usable for linkage',
  '2대 이상 공통 ({0})': 'Shared by 2+ ({0})',
  '설비 하나에만 있는 항목까지 모두 봅니다': 'Shows everything, including items found in only one equipment',
  '전부 ({0})': 'All ({0})',
  'OperationalData의 항목을 <b>semanticId</b>로 묶었습니다. 공정 KPI(OEE·에너지 원단위 등)는 여러 설비의 같은 항목을 모아야 나옵니다. 칸에 마우스를 올리면 그 설비 안의 경로가 보입니다.':
    'OperationalData items are grouped by <b>semanticId</b>. Process KPIs (OEE, energy intensity, …) come from collecting the same item across several equipment. Hover over a cell to see the path inside that equipment.',
  '열린 설비 파일이 없어 분석할 수 없습니다.': 'No equipment file is open, so nothing can be analysed.',
  '설비가 <b>1대</b>라 「공통」 항목이 생길 수 없습니다 — 연계는 설비 2대 이상부터 봅니다(계획서: 공정당 3~5대). 「전부」로 이 설비의 운전 데이터 {0}개를 보십시오.':
    'With only <b>one</b> equipment there can be no "common" items — linkage starts at two (plan: 3–5 per process). Use "All" to see this equipment\'s {0} operational data items.',
  '2대 이상이 함께 가진 항목이 없습니다 — 「전부」로 설비별 항목을 보십시오.': 'No item is shared by two or more equipment — use "All" to see items per equipment.',
  '항목 (semanticId)': 'Item (semanticId)',
  보유: 'Held by',
  '확인할 점이 있습니다 — 아래 목록': 'There are points to check — see the list below',
  '외 {0}': '+{0} more',
  '{0}/{1}대': '{0}/{1}',
  '같은 이름 {0}이(가) 다른 semanticId로 있습니다 — 그대로는 모이지 않습니다\n{1}':
    'The same name {0} exists under a different semanticId — as is, they will not be collected together\n{1}',
  '{0} 같은 이름으로 있음 · {1} 다른 이름으로 있음 · {2} 같은 이름이 <b>다른 semanticId</b>로 있음(그대로는 안 모임) · 숫자는 한 설비 안의 자리 수':
    '{0} present under the same name · {1} present under a different name · {2} same name under <b>a different semanticId</b> (not collected together as is) · numbers are the count of places within one equipment',
  '③ 실동작 증빙 — 수집 기록': '③ Operation evidence — collection record',
  '아직 수집 기록이 없습니다.': 'There is no collection record yet.',
  '이대로 내보내면 번들에 「실제로 값이 흘렀다」는 증빙이 빠집니다.': 'Exported as is, the bundle lacks the evidence that values actually flowed.',
  '이 번들의 설비를 「호기별로 나누기」로 복제하거나, 시연용 번들(호기 파일)을 함께 엽니다':
    'Clone this bundle\'s equipment with "Split into units", or open the demo bundle (unit files) alongside',
  '가상 PLC(또는 현장 PLC)에 수집 연결을 만들고 몇 분 수집합니다 — 자동 수집이면 더 좋습니다':
    'Create a collection link to the virtual PLC (or a field PLC) and collect for a few minutes — automatic collection is better',
  '다시 이 화면에서 내보내면 <code>05_샘플데이터/수집값_*.csv</code>와 <code>06_검증결과/수집기록.html</code>이 실립니다':
    'Export again from this screen and <code>05_샘플데이터/수집값_*.csv</code> and <code>06_검증결과/수집기록.html</code> are included',
  '↩ 이번에 새로 모은 값은 없습니다 — 번들을 열 때 가져온 <b>이전 번들({0} v{1})의 수집 기록</b>을 그대로 이어받아 싣습니다. 새로 수집하면 통째로 새 기록으로 바뀝니다.':
    '↩ No new values were collected this time — <b>the collection record of the previous bundle ({0} v{1})</b>, brought in when the bundle was opened, is carried over as is. Collecting anew replaces it entirely.',
  '번들의 형식 모델은 그대로 두고, <b>그 설비나 거기서 파생된 호기(derivedFrom)</b>에 쌓인 값을 별도 파일로 싣습니다. 현장 주소는 공개 번들이라 가려서 싣습니다.':
    'The type models in the bundle are left as they are; values accumulated on <b>that equipment or units derived from it (derivedFrom)</b> are included as separate files. Field addresses are masked because the bundle is public.',
  이어받음: 'Carried over',
  '건 · 항목 {0}': ' · {0} items',
  '④ 문서·첨부 — Use-Case · 가이던스 · 참고 자료': '④ Documents and attachments — use case, guidance, references',
  '여기 넣은 파일은 번들 ZIP의 해당 폴더에 들어가고, <b>번들을 열었다 다시 내보내도 그대로 남습니다.</b> 공정 파일(AASX)에는 섞이지 않아 해시가 바뀌지 않습니다.':
    'Files added here go into the matching folder of the bundle ZIP, and <b>they stay when the bundle is opened and exported again.</b> They are not mixed into the process file (AASX), so its hash does not change.',
  'Use-Case 문서·가이던스 같은 파일을 번들에 넣습니다 — 번들을 다시 열어도 남습니다': 'Adds files such as the use-case document or guidance to the bundle — they stay when the bundle is reopened',
  '파일 넣기…': 'Add file…',
  '아직 없습니다. 계획서의 번들 구성은 <b>Use-Case 문서 + 참조모델 + 가이던스</b>입니다 — Use-Case 문서와 장비별 가이던스를 넣으십시오.':
    'None yet. The planned bundle composition is <b>use-case document + reference models + guidance</b> — add the use-case document and the guidance for each equipment.',
  '이 파일을 내려받습니다': 'Downloads this file',
  '번들 첨부에서 지웁니다': 'Removes it from the bundle attachments',
  '⑤ 확인할 점': '⑤ Points to check',
  '⚠ 확인': '⚠ Check',
  'ℹ 참고': 'ℹ Info',
  '내보낸 ZIP: <code>00_공정구성 · 01_UseCase문서 · 02_참조모델 · 03_가이던스 · 04_데이터연계정의 · 05_샘플데이터 · 06_검증결과</code>+ <code>bundle-manifest.json</code>(파일마다 SHA256) + <code>README.md</code>. 문서는 작성 안내만 들어갑니다.<br/>✓ 사전 점검은 번들에 넣은 모델을 이 도구가 <b>다시 확인한 참고 표시</b>입니다. 모델의 공식 검증(KOSMO Validator)은 장비별 AASX를 만들 때 받는 것이라 번들에서 따로 하지 않습니다 — 번들 자체의 확인은 해시 대조 · 공정 구성(HIER) · 데이터 연계 · 실동작 증빙으로 합니다.':
    'Exported ZIP: <code>00_공정구성 · 01_UseCase문서 · 02_참조모델 · 03_가이던스 · 04_데이터연계정의 · 05_샘플데이터 · 06_검증결과</code>+ <code>bundle-manifest.json</code> (SHA256 per file) + <code>README.md</code>. Documents contain writing guides only.<br/>✓ The pre-check is <b>a reference mark from this tool re-checking</b> the models in the bundle. The official validation of a model (KOSMO Validator) is obtained when each equipment AASX is made, so it is not repeated for the bundle — the bundle itself is verified by hash comparison, process structure (HIER), data linkage and operation evidence.',

  // ── App — 알림 · 확인 문구 ─────────────────────────────────────────────
  '권한이 없습니다 — 쓰기 권한이 있는 계정이나 토큰으로 다시 들어오십시오.': 'Not permitted — sign in again with an account or token that can write.',
  '파일이 상한을 넘습니다 — {0}': 'The file exceeds the limit — {0}',
  '서버에 연결할 수 없습니다 — API 서버가 꺼져 있거나 네트워크가 끊겼습니다.': 'Cannot reach the server — the API server is down or the network is disconnected.',
  '회사·공정 구성도': 'Company and process structure',
  '이 회사(공정)가 어느 공정·설비로 이루어졌는지 적는 표준 서브모델(IDTA 02011)입니다. 위의 ▦·⚙ 줄은 이 내용을 읽기 좋게 그린 것이고, 파일 안에 실제로 들어 있는 것은 이쪽입니다.':
    'The standard submodel (IDTA 02011) that records which processes and equipment make up this company (process). The ▦·⚙ rows above are a readable drawing of it; this is what is actually stored in the file.',
  '수집 연결': 'Collection link',
  '설비의 OPC UA 주소와 읽을 태그를 적는 표준 서브모델(IDTA 02017 Asset Interfaces Description)입니다. ':
    'The standard submodel (IDTA 02017 Asset Interfaces Description) that records the equipment\'s OPC UA address and the tags to read. ',
  '「수집 연결 만들기」나 「가상 PLC로 연결」을 누르면 이 파일에 더해집니다. 원본 참조모델에는 원래 없으며, ':
    'It is added to this file when you press "Create collection link" or "Connect a virtual PLC". The original reference model does not normally have it, and ',
  '이것이 붙은 파일은 시연본입니다 — 필요 없으면 오른쪽 수집 칸의 「연결 삭제」로 지웁니다.':
    'a file that carries it is a demo copy — remove it with "Delete link" in the collection pane on the right when not needed.',
  '같은 이름의 파일이 이미 열려 있습니다 — 둘 다 유지됩니다. 정리하려면 「파일 목록」에서 지우십시오.':
    'A file with the same name is already open — both are kept. To tidy up, delete one from "File list".',
  '번들 {0} v{1} — 파일 {2}개(새로 {3}) · 해시 일치 {4}/{5}': 'Bundle {0} v{1} — {2} files ({3} new) · hash match {4}/{5}',
  '{0}: {1}이(가) 가리키고 있습니다': '{0}: referenced by {1}',
  '{0}을(를) 목록에서 지웁니다.': 'Delete {0} from the list.',
  '파일 {0}건을 목록에서 지웁니다:\n{1}\n': 'Delete {0} files from the list:\n{1}\n',
  '\n\n주의: {0}. 지우면 그 연결이 끊어집니다.': '\n\nNote: {0}. Deleting breaks that link.',
  '{0} 되돌릴 수 없습니다.{1}': '{0} This cannot be undone.{1}',
  '{0}을(를) 지웠습니다.': 'Deleted {0}.',
  '파일 {0}건을 지웠습니다.': 'Deleted {0} files.',
  묶음: 'group',
  '새 {0} 「{1}」을(를) 만들었습니다. 다만 {2}은(는) 넣지 못했습니다 — 아래에서 다시 넣으십시오.':
    'Created the new {0} "{1}". However, {2} could not be added — add it again below.',
  '새 {0} 「{1}」을(를) {2}건과 함께 만들었습니다.': 'Created the new {0} "{1}" with {2} item(s).',
  '새 {0} 「{1}」을(를) 만들었습니다. 아래 구성 트리의 「＋ 공정」「＋ 설비」로 넣으십시오.':
    'Created the new {0} "{1}". Add to it with "+ Process" and "+ Equipment" in the structure tree below.',
  '새 설비 「{0}」을(를) 만들었습니다. 대표 사진은 임시 그림이니 실제 사진으로 바꾸십시오.':
    'Created the new equipment "{0}". The thumbnail is a placeholder — replace it with a real photo.',
  '값을 저장했습니다.': 'Value saved.',
  '{0} 판으로 되돌립니다. 되돌리기 자체도 이력에 남습니다.': 'Restore the version of {0}. The restore itself is recorded in the history.',
  '되돌렸습니다. 이 되돌리기도 이력에 남아 다시 되돌릴 수 있습니다.': 'Restored. This restore is recorded too, so it can be undone.',
  ' 주의: 이 설비에는 수집 연결(AID)이 있습니다 — ×{0}로 넣으면 수집값이 어느 대의 것인지 구분되지 않습니다. 대별 가동값이 목적이면 대마다 파일을 나누십시오.':
    ' Note: this equipment has a collection link (AID) — added as ×{0}, the collected values cannot be told apart by unit. If you need per-unit values, split it into one file per unit.',
  '「{0}」을(를) {1} 밑에 넣었습니다.': 'Added "{0}" under {1}.',
  '「{0}」을(를) 넣었습니다.': 'Added "{0}".',
  '호기별로 넣다 실패: {0}': 'Failed while adding per unit: {0}',
  '{0}_1 … _{1} 파일을 복제해 나눠 넣었습니다 — 서브모델까지 그대로 담겨 있습니다. 호기마다 값·수집 주소를 따로 고치면 됩니다.':
    'Cloned the file into {0}_1 … _{1} and added them — the submodels are copied as they are. Edit the values and collection addresses per unit.',
  '공정 「{0}」을(를) 만들었습니다. 그 줄의 「＋ 설비」로 설비를 넣으십시오.': 'Created the process "{0}". Add equipment with "+ Equipment" on that row.',
  '「{0}」을(를) 이 목록에서 뺍니다. 설비 파일 자체는 지워지지 않습니다.': 'Remove "{0}" from this list. The equipment file itself is not deleted.',
  '「{0}」을(를) 뺐습니다.': 'Removed "{0}".',
  '대상 파일에 AAS가 없습니다.': 'The target file has no AAS.',
  '「{0}」에 서브모델을 만들었습니다.': 'Created a submodel in "{0}".',
  '이름을 「{0}」(으)로 바꿨습니다.': 'Renamed to "{0}".',
  '「{0}」을(를) 붙였습니다. 내려받기한 AASX 안에 함께 들어갑니다.': 'Attached "{0}". It is included in the downloaded AASX.',
  '붙어 있는 파일을 지웁니다. 계속할까요?': 'This deletes the attached file. Continue?',
  '수집 연결(AID)을 지웁니다.\n\n': 'This deletes the collection link (AID).\n\n',
  '· 이미 수집한 값(시계열)은 남습니다.\n': '· Values already collected (time series) are kept.\n',
  '· 「자리도 함께 만들기」로 OperationalData에 세운 항목도 남습니다 —\n': '· Items created in OperationalData by "create their places too" are kept as well —\n',
  '  필요 없으면 트리에서 직접 지우십시오.\n\n계속할까요?': '  delete them in the tree yourself if not needed.\n\nContinue?',
  '수집 연결을 지웠습니다.': 'Collection link deleted.',
  '대표 사진을 「{0}」(으)로 바꿨습니다. 내려받기한 AASX에 함께 들어갑니다.': 'Thumbnail changed to "{0}". It is included in the downloaded AASX.',
  '용어 「{0}」의 정의를 저장했습니다.': 'Saved the definition of the concept "{0}".',
  '가져왔습니다: {0}': 'Imported: {0}',
  ' · 같은 이름의 옛것 {0}건을 지웠습니다': ' · deleted {0} old one(s) with the same name',
  ' · 이름은 「{0}」로 두었습니다': ' · kept the name "{0}"',
  ' · ConceptDescription {0}건 동반': ' · with {0} ConceptDescription(s)',
  ' — 값은 「{0}」의 것입니다. 트리에서 골라 이 설비 값으로 바꾸십시오.': ' — the values are those of "{0}". Pick them in the tree and change them to this equipment\'s values.',
  '서브모델 {0}': 'Submodel {0}',
  '요소 {0}': 'Element {0}',
  '{0}을(를) 지웁니다. 잘못 지웠으면 「↶ 되돌리기」(Ctrl+Z)로 돌아옵니다.': 'Delete {0}. If it was a mistake, bring it back with "↶ Undo" (Ctrl+Z).',
  '다른 파일의 서브모델은 그 파일을 열어 지우십시오.': 'To delete a submodel of another file, open that file.',
  '「{0}」을(를) 「{1}」(으)로 복제했습니다 — 이름과 값을 고쳐 쓰십시오.': 'Duplicated "{0}" as "{1}" — edit the name and values.',
  '「{0}」을(를) 바로 아래에 복제했습니다.': 'Duplicated "{0}" right below.',
  '수집 {0}건': '{0} collected',
  ' · 접속 실패 {0}건': ' · {0} connection failure(s)',
  ' · 나쁜 태그 {0}건': ' · {0} bad tag(s)',
  '이 설비 파일에 가상 PLC(시뮬레이션) 수집 연결을 만듭니다.\n\n': 'This creates a virtual PLC (simulation) collection link in this equipment file.\n\n',
  '· 파일에 AID 서브모델이 더해져 「시연본」이 됩니다.\n': '· An AID submodel is added and the file becomes a "demo copy".\n',
  '· 원본 참조모델을 그대로 두려면, 먼저 「호기별로 나누기」로 호기를 만들어 거기서 하십시오.\n\n계속할까요?':
    '· To keep the original reference model intact, create units with "Split into units" first and do it there.\n\nContinue?',
  '{0}에 연결했습니다 — 태그 {1}개. 한 번 수집합니다.': 'Connected to {0} — {1} tags. Collecting once.',
  '「{0}」에 가상 PLC(시뮬레이션) 수집 연결을 만듭니다.\n\n': 'This creates a virtual PLC (simulation) collection link in "{0}".\n\n',
  '· 그 설비 파일에 AID 서브모델이 더해져 「시연본」이 됩니다.\n': '· An AID submodel is added to that equipment file and it becomes a "demo copy".\n',
  '· 원본 참조모델이면 먼저 「호기별로 나누기」로 호기를 만들어 거기서 하십시오.\n\n계속할까요?':
    '· If it is the original reference model, create units with "Split into units" first and do it there.\n\nContinue?',
  '「{0}」 {1}에 연결 — 태그 {2}개{3}': '"{0}" connected to {1} — {2} tags{3}',
  ' · 수집 {0}건': ' · {0} collected',
  '「{0}」 수집 {1}건{2}': '"{0}" — {1} collected{2}',
  '되돌렸습니다: {0}. 잘못 눌렀으면 「다시 하기」.': 'Undone: {0}. If that was a mistake, use "Redo".',
  '다시 했습니다: {0}.': 'Redone: {0}.',
  '연결 설비 파일에서 {0}건을 고쳤습니다': 'Fixed {0} in the linked equipment files',
  ' — 다만 {0}는 고치지 못했습니다.': ' — however, {0} could not be fixed.',
  '이관 대장의 {0}건을 IDTA 원본 IRI로 되돌립니다. 지금 정책(KOSMO 우선)이면 다시 위반으로 잡힙니다 — 규정 해석이 바뀌었을 때 쓰는 기능입니다. 잘못 눌렀으면 「↶ 되돌리기」.':
    'Restore {0} entr(ies) of the relocation ledger to the original IDTA IRIs. Under the current policy (KOSMO first) they will be reported as errors again — this is for when the reading of the regulation changes. If it was a mistake, use "↶ Undo".',
  '원본 IRI로 되돌렸습니다: {0}건.': 'Restored to the original IRIs: {0}.',
  '위반 {0}건이 남아 있습니다. 이대로 내려받으면 KOSMO Validator에서 떨어집니다.\n': '{0} errors remain. Downloaded as is, it will fail the KOSMO Validator.\n',
  '그래도 내려받을까요? (작업 중 저장이면 괜찮습니다)': 'Download anyway? (Fine if you are just saving work in progress)',
  'AASX를 내려받았습니다 — 브라우저의 다운로드 폴더에 있습니다.': 'AASX downloaded — it is in your browser\'s download folder.',

  // ── App — 머리줄 · 메뉴 · 창 ─────────────────────────────────────────────
  '처음 화면으로': 'Back to the start screen',
  '제품 판 번호': 'Product version',
  '열기 · 새로 만들기 · 번들 열기 · 파일 목록': 'Open · New · Open bundle · File list',
  '이 PC의 .aasx 파일을 올려 엽니다': 'Upload and open an .aasx file from this PC',
  '빈 설비 또는 회사·공정 묶음을 새로 만듭니다': 'Create a blank equipment file or a company/process group',
  '이 도구로 내보낸 레퍼런스 번들(.zip)을 엽니다 — 공정과 설비가 한 번에 올라옵니다':
    'Open a reference bundle (.zip) exported by this tool — the process and its equipment are loaded at once',
  '올려 둔 파일을 한눈에 보고 지웁니다': 'See the uploaded files at a glance and delete them',
  '눌러서 지적 목록을 봅니다': 'Click to see the findings',
  '이 도구가 다른 시스템에 값을 내주고 있습니다': 'This tool is serving values to other systems',
  '· 변수 {0}개': '· {0} variables',
  '언어 — {0}': 'Language — {0}',
  '화면 글자의 언어를 고릅니다': 'Choose the language of the interface',
  '이 브라우저의 로그인을 끝냅니다': 'End the sign-in on this browser',
  '이 도구가 지키는 규칙 43종과 규약을 지금 도는 그대로 보여 줍니다':
    'Shows the 43 rules and the conventions this tool enforces, exactly as they are running now',
  '이 브라우저에 저장된 접근 토큰을 지웁니다 — 공용 PC에서 자리를 뜰 때':
    'Clear the access token stored in this browser — when leaving a shared PC',
  되돌리기: 'Undo',
  '되돌리기: {0} (Ctrl+Z){1}': 'Undo: {0} (Ctrl+Z){1}',
  ' · {0}단계 남음': ' · {0} step(s) left',
  '되돌릴 변경이 없습니다': 'Nothing to undo',
  '다시 하기': 'Redo',
  '다시 하기: {0} (Ctrl+Shift+Z)': 'Redo: {0} (Ctrl+Shift+Z)',
  '다시 할 변경이 없습니다': 'Nothing to redo',
  '이 파일에 서브모델을 넣습니다': 'Add a submodel to this file',
  '이 설비에 새 서브모델을 만듭니다 — id는 규약대로 지어집니다': 'Create a new submodel for this equipment — the id follows the convention',
  '다른 AASX의 서브모델을 통째로 복사합니다 — 용어(CD)도 함께 옵니다':
    'Copy a whole submodel from another AASX — its concept descriptions (CD) come along',
  '자동으로 고칠 지적이 없습니다 — {0}건은 사람이 판단할 몫입니다(지적 목록 참조)':
    'Nothing to fix automatically — {0} finding(s) need a human decision (see the findings)',
  '자동으로 고칠 지적이 없습니다': 'Nothing to fix automatically',
  '고칠 수 있는 지적을 규약대로 교정합니다 — 설비 파일 것은 그 설비 파일에 저장됩니다':
    'Fix the fixable findings by the conventions — those of an equipment file are saved to that file',
  '고칠 수 있는 지적(경고 포함)을 규약대로 자동 교정합니다': 'Automatically fix the fixable findings (warnings included) by the conventions',
  '검증 결과서 · 문서용 자료 · 번들을 내보냅니다': 'Export the validation report, document material and bundles',
  '검사 결과를 인쇄용으로 엽니다 — 인쇄하면 그대로 PDF로 저장할 수 있습니다':
    'Open the check result for printing — you can save it as a PDF from the print dialog',
  '가이던스에 붙일 UML 그림과 표를 뽑습니다': 'Produce the UML diagrams and tables for the guidance document',
  '이 공정을 ZIP 묶음으로 봅니다 — 구성·준비 상태·데이터 연계':
    'View this process as a ZIP package — structure, readiness, data links',
  '위반 {0}건이 남아 있습니다 — 받을 수는 있지만 KOSMO 규칙을 아직 다 지키지 못했습니다':
    '{0} error(s) remain — you can download it, but it does not yet meet every KOSMO rule',
  '지금 파일을 .aasx로 내려받습니다': 'Download this file as an .aasx',
  '접근 토큰이 필요합니다.': 'An access token is required.',
  '관리자에게 받은 토큰을 넣어 주세요.': 'Enter the token you received from the administrator.',
  토큰: 'Token',
  '다른 곳에서 이 서브모델이 먼저 바뀌었습니다.': 'This submodel was changed elsewhere first.',
  '내 수정은 저장하지 않았습니다.': 'Your edit was not saved.',
  '서버에 저장된 최신 내용을 다시 읽어 옵니다 — 내가 고치던 것은 사라집니다':
    'Reload the latest content stored on the server — what you were editing is lost',
  '교정 {0}건({1}바퀴) · 남은 위반 {2}건': '{0} fixed ({1} round(s)) · {2} error(s) remaining',
  '· 이관 대장 {0}건': '· {0} in the relocation ledger',
  '규칙과 규약': 'Rules and conventions',
  '트리에서 찾기': 'Find in the tree',
  '찾기 — 이름·값·semanticId': 'Find — name, value, semanticId',
  '찾는 말을 지웁니다': 'Clear the search',
  '이 구성에서 빼기': 'Remove from this structure',
  '이 설비 파일 열기': 'Open this equipment file',
  '잘못 지웠으면 헤더의 ↶ 되돌리기': 'If it was a mistake, use ↶ Undo in the header',
  '안의 요소와 값까지 그대로 하나 더 (이름 끝에 _2)': 'One more copy with its elements and values (name ends with _2)',
  트리: 'Tree',
  '열린 파일 {0}건': '{0} open file(s)',
  '{0} 고르기': 'Select {0}',
  '이 파일 열기': 'Open this file',
  '서버에서 이 파일을 지웁니다 — 되돌릴 수 없습니다. 내려받아 둔 .aasx는 남습니다':
    'Delete this file from the server — this cannot be undone. Any .aasx you downloaded stays',
  '체크한 파일을 한 번에 지웁니다': 'Delete the checked files at once',
  '고른 {0}건 지우기': 'Delete {0} selected',
  '지우면 되돌릴 수 없습니다. 내려받아 둔 .aasx 파일은 남습니다.': 'Deleting cannot be undone. Any .aasx files you downloaded stay.',
  '파일: {0}': 'File: {0}',
  '이 설비 파일에 서브모델을 만듭니다 — 지금 보는 공정 파일이 아니라 그 설비 파일에 저장됩니다':
    'Create a submodel in this equipment file — it is saved to that equipment file, not the process file you are viewing',
  '밑에 펼쳐진 서브모델·요소는 여기서 바로 고칠 수 있습니다 — 저장하면 이 설비 파일이 바뀝니다.':
    'The submodels and elements expanded below can be edited right here — saving changes this equipment file.',
  '오른쪽 칸': 'Right pane',
  '새 파일을 만들고 있습니다. 수집 연결은 파일이 만들어진 뒤 이 자리에서 잇습니다.':
    'Creating a new file. The collection link is set up here once the file exists.',
  '내주는 중': 'Serving',
  '내주기 창 닫기': 'Close the serving window',
  '→ 다른 시스템에 값 내주는 중': '→ Serving values to other systems',
  '[설비·PLC] ──▶ <b>[이 도구]</b> ──▶ [MES·SCADA]': '[Equipment·PLC] ──▶ <b>[This tool]</b> ──▶ [MES·SCADA]',
  '작성한 AAS를 OPC UA 서버로 내주고 있습니다. 상위 앱이 <b>구독</b>으로 값을 받아 갑니다 — 값이 바뀌면 이쪽에서 먼저 알립니다.':
    'The authored AAS is being served through an OPC UA server. Upper-level applications receive values by <b>subscription</b> — this side notifies them when a value changes.',
  '상위 앱에 알려 줄 주소': 'Address to give to upper-level applications',
  '내주는 파일': 'Files being served',
  '{0}개 · 변수 {1}개': '{0} · {1} variables',
  '주의 — 이 주소는 <b>남이 접속해 올 주소</b>입니다. 수집 연결의 「설비 주소」 칸에 넣는 주소가 아닙니다 — 거기 넣으면 우리가 내준 값을 우리가 다시 읽게 됩니다.':
    'Note — this is <b>the address others connect to</b>. It is not the address for the "Endpoint" field of a collection link — entered there, we would read back the values we serve ourselves.',
  '전부 읽기 전용입니다. 밖에서 값을 바꿀 수 없습니다.': 'Everything is read-only. Values cannot be changed from outside.',
  '자동 고치기 미리보기': 'Auto-fix preview',
  '지적 목록': 'Findings',
  '지적 목록 닫기': 'Close the findings',
  // ── 설정 ────────────────────────────────────────────────────────────────
  '화면 글자를 영어로 — 서버가 만드는 글(지적 문구·검증 결과서)은 한국어로 남습니다':
    'Switch the interface to English — text produced by the server (finding messages, validation report) stays Korean',
  '영어는 <b>화면 글자</b>까지 옮겼습니다. 지적 문구·규칙 설명·검증 결과서는 서버가 만드는 글이라 아직 한국어로 나옵니다 — 섞여 보이는 것이 정상입니다.':
    'English covers <b>the interface</b>. Finding messages, rule descriptions and the validation report are produced by the server and are still Korean — seeing both mixed is expected.',
  '언어를 바꾸면 화면을 새로 읽습니다 — 파일은 그대로 있고, 저장하지 않은 입력만 사라집니다.':
    'Changing the language reloads the page — your files stay as they are; only unsaved input is lost.',

  // ── 로그인 — 가입이 닫힌 서버 ─────────────────────────────────────────
  '계정이 없으면 관리자에게 요청하십시오 — 관리자가 「설정 → 계정 관리」에서 만들어 줍니다.':
    'No account? Ask your administrator — they can create one in "Settings → Manage accounts".',

  // ── 첫 화면 — 견본으로 시작하기 ─────────────────────────────────────
  '견본 파일을 받지 못했습니다 ({0}).': 'Could not fetch the sample file ({0}).',
  '견본을 열었습니다 — 공정 구성(RB01)과 설비 1종(RollFormingMachine_sample ×2). 설비 줄을 누르면 그 설비 파일이 열립니다.':
    'Sample opened — a process structure (RB01) and one equipment type (RollFormingMachine_sample ×2). Click an equipment row to open that equipment file.',
  'AASX 파일이 아직 없다면 — ': 'No AASX file yet? — ',
  '다 채워진 설비 1종과 공정 구성을 열어 둘러봅니다 — 고쳐도 되는 연습용입니다':
    'Opens a fully filled equipment file and a process structure to explore — safe to edit for practice',
  '견본으로 시작하기': 'Start with a sample',

  '견본 열기': 'Open sample',

  // ── 로그인 화면 — 로그인 위 · 체험 아래 ───────────────────────────────
  'AAS를 만들고 · 검사하고 · 내려받는 웹 도구입니다.': 'A web tool to create, validate and download AAS.',
  '가입 없이 먼저 써 보기': 'Try it without signing up',
  '처음이신가요? 회원가입': 'New here? Sign up',

  // ── 회원가입 — 회사명 · 이메일 · 동의 (2026-10-06) ─────────────────────
  회사명: 'Company',
  이메일: 'Email',
  '이름 · 회사명 · 이메일을 모두 적어 주십시오.': 'Please fill in your name, company and email.',
  '개인정보 수집·이용에 동의해야 가입할 수 있습니다.': 'You need to agree to the collection and use of personal information to sign up.',
  '확인 메일은 보내지 않습니다.': 'No confirmation email is sent.',
  '개인정보 수집·이용 동의 (필수)': 'Consent to collection and use of personal information (required)',
  '아이디 · 이름 · 회사명 · 이메일 · 비밀번호(암호화 저장)': 'Login ID · name · company · email · password (stored hashed)',
  목적: 'Purpose',
  '회원 식별 · 서비스 제공 · 문의 응대': 'Member identification · providing the service · answering inquiries',
  '보유 기간': 'Retention',
  '탈퇴할 때까지 — 탈퇴하면 올린 파일과 함께 지웁니다': 'Until you delete your account — your uploaded files are deleted with it',
  '동의하지 않을 수 있으나, 그 경우 가입할 수 없습니다. 가입 없이 데모 계정으로 써 볼 수 있습니다.':
    'You may decline, but then you cannot sign up. You can still try the service with the demo account.',
  '위 내용과 ': 'I agree to the above and the ',
  동의: 'Consent',

  // ── 계정 관리 — 삭제 (2026-10-06) ─────────────────────────────────────
  '계정과 그 사람이 올린 파일을 지웁니다 — 되돌릴 수 없습니다. 막기만 하려면 「잠그기」':
    'Deletes the account and the files that person uploaded — this cannot be undone. To only block access, use "Lock"',
  '「{0}」({1}) 계정을 지웁니다.\n\n그 사람이 올린 파일도 함께 지워지며 되돌릴 수 없습니다.\n막기만 하려면 「잠그기」를 쓰십시오.\n\n지울까요?':
    'Delete the account "{0}" ({1}).\n\nThe files this person uploaded are deleted too, and this cannot be undone.\nTo only block access, use "Lock".\n\nDelete?',
  '「{0}」 계정을 지웠습니다.': 'Deleted the account "{0}".',

  // ── 계정 관리 ──
  데모: 'demo',

  // ── 내 계정 설정 (2026-10-08) ──
  '사람을 더하고, 역할을 바꾸고, 잠급니다': 'Add people, change roles and lock accounts',
  '내 계정 설정': 'My account',
  '내 이름 · 회사명 · 이메일 · 비밀번호를 바꿉니다': 'Change my name, company, email and password',
  '내 정보를 저장했습니다.': 'Saved my details.',
  '내 정보': 'My details',
  '역할: {0} — 역할은 관리자가 「계정 관리」에서 바꿉니다.': 'Role: {0} — an administrator changes roles in "Accounts".',
  '비밀번호는 10자 이상이어야 합니다. 바꾸면 다른 곳의 로그인은 끊깁니다.': 'At least 10 characters. Changing it signs you out everywhere else.',
  '내 계정 설정 →': 'My account →',
  '내 이름 · 연락처 · 비밀번호는 여기서 바꿉니다.': 'Change your own name, contact details and password there.',

  // ── 회원가입 — 회사명 선택 · 필수 표시 (2026-10-08) ──
  '이름 · 이메일을 적어 주십시오.': 'Please enter your name and email.',
  '(선택)': '(optional)',
  '아이디 · 이름 · 이메일 · 비밀번호(암호화 저장) · 회사명(선택)': 'Login name · name · email · password (stored encrypted) · company (optional)',

  // ── 화면 안 도움말 · 따라 하기 안내 · 시작하기 목록 (2026-10-08) ──
  '파일 열기': 'Open a file',
  '내 PC의 AASX를 올려 열어 보세요': 'Upload and open an AASX from your PC',
  '견본이나 내 AASX를 열어 보세요': 'Open the sample or your own AASX',
  '검사 결과 보기': 'View the check result',
  '머리줄의 「위반 · 경고」를 누르세요': 'Press "Errors · Warnings" in the header',
  '먼저 파일을 여세요': 'Open a file first',
  '미리 보고 고치기': 'Preview and fix',
  '「자동 고치기」로 고칠 항목을 전 / 후로 확인합니다': 'Use "Auto-fix" to see each fix before / after',
  '회원가입하고 내려받기': 'Sign up to download',
  '데모 계정은 내려받기가 막혀 있습니다': 'The demo account cannot download files',
  '파일 내려받기': 'Download the file',
  '완성본을 .aasx로 받습니다': 'Download the finished file as .aasx',
  '이 화면에서 할 수 있는 일과 쓰는 법을 봅니다 (F1)': 'See what you can do on this screen and how (F1)',
  '? 도움말': '? Help',
  시작하기: 'Get started',
  '시작하기 목록 닫기': 'Close the getting-started list',
  도움말: 'Help',
  '도움말 닫기': 'Close help',
  '무엇을 찾으세요? 예: 내려받기': 'What are you looking for? e.g. download',
  '도움말 찾기': 'Search help',
  '▶ 화면 둘러보기': '▶ Take the tour',
  '시작하기 목록 보기': 'Show the getting-started list',
  '찾는 내용이 없습니다. 다른 말로 찾아보세요.': 'Nothing found. Try other words.',
  '지금 화면': 'This screen',
  '검사 규칙의 자세한 설명은 「설정 ▾ → 규칙과 규약 보기」에 있습니다.': 'Detailed rule descriptions are in "Settings ▾ → Rules and conventions".',
  '화면 둘러보기': 'Tour',
  건너뛰기: 'Skip',
  이전: 'Back',
  마치기: 'Finish',
  다음: 'Next',
  '회원은 로그인, 처음이면 회원가입. 가입 없이 데모 계정으로도 둘러볼 수 있습니다.': 'Members sign in; newcomers sign up. You can also look around with the demo account without signing up.',
  '회원 — 로그인 이름과 비밀번호를 넣고 「로그인」': 'Members — enter your login name and password, then "Sign in"',
  '처음이면 — 「처음이신가요? 회원가입」. 가입하면 작업한 파일을 내려받을 수 있습니다': 'New here — "New here? Sign up". Members can download their work',
  '데모 계정 — 공용 계정이라 파일 내려받기와 견본 열기가 막혀 있고, 일정 시간 후 초기화 됩니다': 'Demo account — a shared account: downloads and the sample are locked, and it is reset after a while',
  '비밀번호를 5번 틀리면 5분 동안 그 계정으로 로그인할 수 없습니다.': 'After 5 wrong passwords the account is blocked for 5 minutes.',
  '화면 구성': 'Screen layout',
  '머리줄 아래에 트리 · 내용 · 수집 세 칸이 있습니다.': 'Below the header are three panes: tree · content · collection.',
  '머리줄 — 파일 · 서브모델 · 자동 고치기 · 검사 결과 · 내보내기 · 내려받기 · 설정': 'Header — File · Submodel · Auto-fix · check result · Export · Download · Settings',
  '트리(왼쪽) — AAS → 서브모델 → 요소 순서로 펼쳐집니다. 고르면 가운데에 내용이 나옵니다': 'Tree (left) — AAS → submodel → element. Pick one to see it in the middle',
  '내용(가운데) — 요약 · 값 고치기 · 부품 구성': 'Content (middle) — summary · editing values · parts structure',
  '수집(오른쪽) — 설비에서 값을 가져옵니다(OPC UA)': 'Collection (right) — reads values from the machine (OPC UA)',
  '칸 사이 경계를 끌면 너비를 바꿀 수 있습니다.': 'Drag the border between panes to resize them.',
  '내 PC의 AASX를 올리거나, 새로 만들거나, 견본으로 시작합니다.': 'Upload an AASX from your PC, create a new one, or start from the sample.',
  '「AASX 파일 열기」 — 내 PC의 .aasx를 올려 엽니다': '"Open an AASX file" — uploads and opens an .aasx from your PC',
  '「새로 만들기」 — 설비 한 대 또는 회사 · 공정 그룹. 필수 서브모델 4종이 자동으로 들어갑니다': '"New" — one machine or a company · process group. The 4 required submodels are added for you',
  '「번들 열기」 — 이 도구에서 내보낸 레퍼런스 번들(.zip)을 엽니다': '"Open a bundle" — opens a reference bundle (.zip) exported by this tool',
  '「견본으로 시작하기」 — 내용이 채워진 연습용 견본(회원)': '"Start with a sample" — a filled-in practice sample (members)',
  '같은 파일을 다시 올리면 사본이 생깁니다. 작업하던 파일은 「파일 ▾ → 파일 목록」에서 고르세요.': 'Uploading the same file again makes a copy. Pick your work in progress from "File ▾ → File list".',
  '값 고치기': 'Editing values',
  '왼쪽 트리에서 요소를 고르면 가운데에서 고칩니다. 저장하면 서버에 바로 반영됩니다.': 'Pick an element in the tree and edit it in the middle. Saving updates the server right away.',
  '요소 하나 — 트리에서 고르고 값을 바꾼 뒤 「저장」': 'One element — pick it in the tree, change the value, then "Save"',
  '한꺼번에 — 서브모델을 고르면 「값 한꺼번에 입력」 표가 나옵니다': 'Many at once — pick a submodel to get the "Enter values in bulk" table',
  '가져오기 — 「서브모델 ▾ → 다른 파일에서 가져오기」로 견본의 서브모델을 통째로 복사': 'Import — "Submodel ▾ → Import from another file" copies a whole submodel from the sample',
  '되돌리기 — 머리줄 「↶ 되돌리기」(Ctrl+Z), 지난 시점은 「이력 · 되돌리기」': 'Undo — "↶ Undo" in the header (Ctrl+Z); earlier versions via "History · revert"',
  '가져온 값은 원본 설비의 값입니다. 이 설비에 맞게 고쳐 주세요.': 'Imported values belong to the source machine. Adjust them for this machine.',
  '검사와 자동 고치기': 'Checks and auto-fix',
  '파일을 열면 규칙 43종으로 바로 검사합니다. 위반은 반드시 고칩니다.': 'Opening a file checks it against 43 rules right away. Errors must be fixed.',
  '머리줄의 「위반 · 경고」를 누르면 검사 결과가 열립니다': 'Press "Errors · Warnings" in the header to open the check result',
  '위반(빨강) — KOSMO 규칙에 어긋남. 0건이 되도록 고칩니다': 'Errors (red) — break a KOSMO rule. Fix them until there are none',
  '경고(노랑) — 표준 · 상호운용에 문제가 될 수 있음. 항목을 누르면 그 요소로 갑니다': 'Warnings (yellow) — may cause standard / interoperability problems. Click an item to jump to it',
  '「자동 고치기」 — 전 / 후를 미리 보고, 체크한 것만 고칩니다': '"Auto-fix" — preview before / after and fix only what you tick',
  '이 도구의 검사는 사전 점검입니다. 공식 판정은 KOSMO Validator가 합니다.': 'This tool runs a pre-check. The official verdict comes from the KOSMO Validator.',
  '검증 결과서 · 문서용 자료 · AASX를 내려받습니다.': 'Download the validation report, document material and the AASX.',
  '「내보내기 ▾ → 검증 결과서」 — 인쇄 메뉴에서 PDF로 저장': '"Export ▾ → Validation report" — save as PDF from the print dialog',
  '「내보내기 ▾ → 문서용 자료」 — UML 그림 · 표 · .docx': '"Export ▾ → Document material" — UML diagrams · tables · .docx',
  '「AASX 내려받기」 — 지금 파일을 .aasx로(회원만)': '"Download AASX" — this file as .aasx (members only)',
  '완성본은 위반 0건 상태에서 내려받으세요.': 'Download the finished file once there are no errors.',
  '공정과 레퍼런스 번들': 'Processes and reference bundles',
  '회사 → 공정 → 설비를 한 트리로 묶고, ZIP 하나로 내보냅니다.': 'Group company → process → machines in one tree and export them as one ZIP.',
  '「새로 만들기 → 그룹(회사 · 공정)」으로 공정 파일을 만듭니다': 'Create a process file with "New → Group (company · process)"',
  '「＋ 공정」 「＋ 설비」로 구성합니다. 같은 기종 여러 대는 ×N': 'Build it with "＋ Process" and "＋ Machine". Several of the same model: ×N',
  '공정 파일에서 「내보내기 ▾ → 레퍼런스 번들」 — 구성 · 준비 상태를 보고 ZIP으로': 'From the process file, "Export ▾ → Reference bundle" — review structure and readiness, then ZIP',
  '현장 값 수집': 'Collecting field values',
  '오른쪽 「수집」 칸에서 설비(PLC)의 값을 가져옵니다.': 'The "Collection" pane on the right reads values from the machine (PLC).',
  '실제 PLC가 없으면 「가상 PLC로 연결」 — 바로 시험할 수 있습니다': 'No real PLC? "Connect a virtual PLC" — try it right away',
  '실제 설비는 「수집 연결 만들기」 — OPC UA 주소와 태그를 넣습니다': 'For a real machine, "Create collection link" — enter the OPC UA address and tags',
  '「수집」 — 지금 값을 한 번 읽어 옵니다. 「주소 목록」으로 수집 주소 표(CSV)': '"Collect" — reads the current values once. "Address list" gives the address table (CSV)',
  '연결하면 파일에 수집 연결(AID)이 추가되어 「시연본」이 됩니다. 원본 파일에는 연결하지 마세요.': 'Connecting adds a collection link (AID) and makes the file a demo copy. Do not connect the original file.',
  '내 계정': 'My account',
  '「설정 ▾」에서 언어 · 내 계정 설정 · 로그아웃 · 탈퇴를 합니다.': '"Settings ▾" holds language · my account · sign out · delete account.',
  '「내 계정 설정」 — 표시 이름 · 회사명 · 이메일 · 비밀번호': '"My account" — display name · company · email · password',
  '「언어」 — 한국어 / English(이 브라우저에만 저장)': '"Language" — 한국어 / English (saved in this browser only)',
  '「탈퇴」 — 계정과 올린 파일이 바로 삭제되며 되돌릴 수 없습니다': '"Delete account" — your account and uploads are deleted at once and cannot be restored',
  '비밀번호를 잊었다면 관리자에게 「비밀번호 초기화」를 요청하세요.': 'Forgot your password? Ask an administrator to reset it.',
  '내 PC의 .aasx 파일을 올려 엽니다. 여기서부터 시작합니다.': 'Upload and open an .aasx file from your PC. Start here.',
  '파일이 없다면 설비 한 대나 회사 · 공정 그룹을 새로 만듭니다.': 'No file yet? Create one machine or a company · process group.',
  '내용이 채워진 연습용 견본입니다. 처음이라면 이것부터 열어 보세요(회원).': 'A filled-in practice sample. If you are new, open this first (members).',
  '파일 메뉴': 'File menu',
  '열기 · 새로 만들기 · 번들 · 파일 목록은 언제든 여기서 다시 찾습니다.': 'Open · new · bundle · file list are always here.',
  '막히면 「? 도움말」을 누르세요. 지금 화면에 맞는 설명이 먼저 나옵니다(F1).': 'Stuck? Press "? Help" — it opens on the topic for this screen (F1).',
  'AAS → 서브모델 → 요소 순서입니다. 고르면 가운데에 내용이 나옵니다.': 'AAS → submodel → element. Pick one to see it in the middle.',
  '요약 · 값 고치기 · 부품 구성이 여기에 나옵니다. 값을 바꾸고 「저장」을 누르세요.': 'Summary, value editing and parts structure appear here. Change a value and press "Save".',
  '검사 결과': 'Check result',
  '파일을 열면 규칙 43종으로 바로 검사합니다. 누르면 무엇이 어긋났는지 보입니다.': 'Opening a file checks it against 43 rules. Click to see what is wrong.',
  '고칠 수 있는 항목을 전 / 후로 미리 보고, 고른 것만 고칩니다.': 'Preview fixable items before / after and fix only the ones you pick.',
  '검증 결과서 · 문서용 자료 · 레퍼런스 번들을 만듭니다.': 'Makes the validation report, document material and reference bundles.',
  '지금 파일을 .aasx로 받습니다(회원). 완성본은 위반 0건 상태에서 받으세요.': 'Downloads this file as .aasx (members). Download the finished file once there are no errors.',
  '설비에서 값을 가져옵니다. 실제 PLC가 없으면 「가상 PLC로 연결」로 시험해 보세요.': 'Reads values from the machine. No real PLC? Try "Connect a virtual PLC".',

  '왼쪽 위 「VEXPLOR AAS Studio」 — 누르면 언제든 첫 화면으로 돌아갑니다(열어 둔 파일은 그대로)': 'Top-left "VEXPLOR AAS Studio" — click it to return to the start screen any time (open files stay open)',
  '첫 화면으로': 'Back to start',
  '왼쪽 위 「VEXPLOR AAS Studio」를 누르면 언제든 이 첫 화면으로 돌아옵니다.': 'Click "VEXPLOR AAS Studio" at the top left to come back to this start screen any time.',
  '왼쪽 위 「VEXPLOR AAS Studio」를 누르면 첫 화면으로 돌아갑니다. 열어 둔 파일은 그대로 남아, 위쪽 파일 고르개에서 다시 엽니다.': 'Click "VEXPLOR AAS Studio" at the top left to return to the start screen. Your open file stays; reopen it from the file picker at the top.',
};
